- name: install java
  sudo: true
  apt: pkg=openjdk-7-jre-headless state=latest

- name: download
  sudo: true
  get_url: >
    url={{ elasticsearch.deb_url }}
    sha256sum={{ elasticsearch.deb_sha256 }}
    dest=/opt/elasticsearch.deb
    owner=root
    group=root
    mode=0644

- name: install
  sudo: true
  apt: deb=/opt/elasticsearch.deb
  notify: restart elasticsearch

- name: configure
  sudo: true
  copy: >
    content='{{ elasticsearch.config | to_nice_yaml }}'
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=root
    mode=0644
  notify: restart elasticsearch
