- name: install java
  sudo: true
  apt: pkg=openjdk-7-jre-headless state=latest

- name: download
  sudo: true
  get_url: >
    url={{ elasticsearch.deb_url }}
    sha256sum={{ elasticsearch.deb_sha256 }}
    dest=/opt/elasticsearch.deb
    owner=root
    group=root
    mode=0644

- name: install
  sudo: true
  apt: deb=/opt/elasticsearch.deb
  notify: restart elasticsearch

- name: configure
  sudo: true
  copy: >
    content='{{ elasticsearch.config | to_nice_yaml }}'
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=root
    mode=0644
  notify: restart elasticsearch

- name: enable
  sudo: true
  service: name=elasticsearch enabled=true

- name: install python-passlib
  sudo: true
  apt: pkg=python-passlib

- name: generate htpasswd
  sudo: true
  htpasswd: >
    path=/etc/nginx/elasticsearch.htpasswd
    name={{ elasticsearch.username }}
    password={{ elasticsearch.password }}
    owner=root
    group=www-data
    mode=0640
  notify: reload nginx

- name: generate vhost
  sudo: true
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/sites-enabled/elasticsearch
    owner=root
    group=root
    mode=0644
  notify: reload nginx
