- name: create log directory
  sudo: true
  file: >
    path=/var/log/proxxy
    owner=root
    group=root
    mode=0755
    state=directory

- name: create cache directory
  sudo: true
  file: >
    path=/var/cache/proxxy
    owner=www-data
    group=root
    mode=0770
    state=directory

- name: generate nginx.conf
  sudo: true
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0600
  notify: reload nginx

- name: generate vhosts
  sudo: true
  template: >
    src=nginx-vhosts.conf.j2
    dest=/etc/nginx/sites-enabled/proxxy
    owner=root
    group=root
    mode=0600
  notify: reload nginx

- name: generate logstash config
  sudo: true
  template: >
    src=logstash.conf.j2
    dest=/etc/logstash/conf.d/proxxy.conf
    owner=root
    group=root
    mode=0644
  notify: restart logstash
