- name: add APT key
  sudo: true
  apt_key: >
    id=A88D21E9
    keyserver=keyserver.ubuntu.com

- name: add APT repository
  sudo: true
  apt_repository: >
    repo='deb https://get.docker.io/ubuntu docker main'
    update_cache=true

- name: install Docker
  sudo: true
  apt: pkg=lxc-docker

- name: add current user to 'docker' group
  sudo: true
  user: >
    name={{ ansible_ssh_user }}
    groups=docker
    append=true
