- name: download
  sudo: true
  get_url: >
    url={{ kibana.tgz_url }}
    sha256sum={{ kibana.tgz_sha256 }}
    dest=/opt/kibana.tgz
    owner=root
    group=root
    mode=0644

- name: create directory
  sudo: true
  file: >
    path=/opt/kibana
    owner=root
    group=root
    mode=0755
    state=directory

- name: extract
  sudo: true
  command: >
    tar -xf /opt/kibana.tgz -C /opt/kibana --strip-components=1
    creates=/opt/kibana/index.html

- name: generate config.js
  sudo: true
  template: >
    src=config.js.j2
    dest=/opt/kibana/config.js
    owner=root
    group=root
    mode=0644

- name: switch default dashboard to logstash
  sudo: true
  command: >
    mv /opt/kibana/app/dashboards/logstash.json /opt/kibana/app/dashboards/default.json
    removes=/opt/kibana/app/dashboards/logstash.json

- name: generate vhost
  sudo: true
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/sites-enabled/kibana
    owner=root
    group=root
    mode=0644
  notify: reload nginx
