- name: download
  sudo: true
  get_url: >
    url={{ logstash.deb_url }}
    sha256sum={{ logstash.deb_sha256 }}
    dest=/opt/logstash.deb
    owner=root
    group=root
    mode=0644

- name: install
  sudo: true
  apt: deb=/opt/logstash.deb
  notify: restart logstash

- name: generate outputs.conf
  sudo: true
  template: >
    src=outputs.conf.j2
    dest=/etc/logstash/conf.d/outputs.conf
    owner=root
    group=root
    mode=0644
  notify: restart logstash
